### PR TITLE
Fix electrum API encoding

### LINKED ISSUE #1974: Electrum backend failure (introduced in 543c1ce)
When running mempool with backend `electrum`, address-related API functions fail with error `sha256 is not a function`.
Example:
```
curl -s http://localhost:8999/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv; echo
curl -s https://mempool.nixbitcoin.org/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv; echo
#=> sha256 is not a function
```
Bisecting shows that this error was introduced in https://github.com/mempool/mempool/commit/543c1cee62db5e1f396e3d713bae51b955cc4522.

I've reproduced this by building the backend like in `ci.yml` and running it in a nix-bitcoin container environment. So this bug  should be easily reproducible with docker.

### PR DESCRIPTION
**Pull request by knorrium**
Fix #1974 

attn @erikarvstedt

After the fix:
```
$ curl -s http://localhost:8999/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv | jq
{
  "address": "1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv",
  "chain_stats": {
    "funded_txo_count": 0,
    "funded_txo_sum": 29356,
    "spent_txo_count": 0,
    "spent_txo_sum": 0,
    "tx_count": 9
  },
  "mempool_stats": {
    "funded_txo_count": 0,
    "funded_txo_sum": 0,
    "spent_txo_count": 0,
    "spent_txo_sum": 0,
    "tx_count": 0
  },
  "electrum": true
}
```

Umbrel @ 2.4.0

```
curl -s http://10.21.21.27:8999/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv  | jq
{
  "address": "1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv",
  "chain_stats": {
    "funded_txo_count": 0,
    "funded_txo_sum": 29356,
    "spent_txo_count": 0,
    "spent_txo_sum": 0,
    "tx_count": 9
  },
  "mempool_stats": {
    "funded_txo_count": 0,
    "funded_txo_sum": 0,
    "spent_txo_count": 0,
    "spent_txo_sum": 0,
    "tx_count": 0
  },
  "electrum": true
}
```

### CODE REVIEW

**Review by wiz — APPROVED** [review]
utACK
