### ISSUE TITLE
Error building backend on node v16.15.0

### ISSUE THREAD

**Issue by darthginger** [mempool/mempool#1608]
### Description
building the backend on a fresh git clone fails.

#### Version
https://github.com/mempool/mempool/commit/da3c7588b86cd1287364be9e7123c304fece8549
node: v16.15.0 (Latest LTS)
npm: 8.5.5

### Steps to reproduce
git clone mempool, cd backend, npm install --prod, npm run build, error

#### Device or machine
debian 11, amd64

#### Additional info
Original Error: https://pastebin.com/tvaRip7C

I also tried the suggestion in the error and did `npm i --save-dev @types/node`:
After that the npm run build:
```
npm run build

> mempool-backend@2.4.0-dev build
> npm run tsc


> mempool-backend@2.4.0-dev tsc
> ./node_modules/typescript/bin/tsc

src/api/disk-cache.ts:20:18 - error TS2339: Property 'isMaster' does not exist on type 'typeof import("cluster")'.

20     if (!cluster.isMaster) {
                    ~~~~~~~~

src/index.ts:47:17 - error TS2339: Property 'isMaster' does not exist on type 'typeof import("cluster")'.

47     if (cluster.isMaster) {
                   ~~~~~~~~

src/index.ts:53:32 - error TS2339: Property 'fork' does not exist on type 'typeof import("cluster")'.

53         const worker = cluster.fork(env);
                                  ~~~~

src/index.ts:57:15 - error TS2339: Property 'on' does not exist on type 'typeof import("cluster")'.

57       cluster.on('exit', (worker, code, signal) => {
                 ~~

src/index.ts:62:37 - error TS2339: Property 'fork' does not exist on type 'typeof import("cluster")'.

62           const newWorker = cluster.fork(env);
                                       ~~~~

src/index.ts:109:73 - error TS2339: Property 'isMaster' does not exist on type 'typeof import("cluster")'.

109     if (config.STATISTICS.ENABLED && config.DATABASE.ENABLED && cluster.isMaster) {
                                                                            ~~~~~~~~


Found 6 errors in 2 files.

Errors  Files
     1  src/api/disk-cache.ts:20
     5  src/index.ts:47
```
Frontend builds fine btw

**Comment by wiz** [comment]
We specify to use node v16.10.0 in the production installation instructions, please use that instead of v16.15 if you have issues

**Comment by darthginger** [comment]
Ok i switched to v16.10.0 and got the same error so i tracked down at which commit this problem starts and it is this one: 5336ba8160b75307f3abfe37cbaff30d57378257 I tried around 10 commits before that in a range of a month and a couple after that to confirm. Commits before build fine on v16.10.0 commits after throw the error from the pastebin.

**Comment by wiz** [comment]
mempool.space is running master branch just fine

**Comment by darthginger** [comment]
i found the problem: yes it has to be v16.10.0, but also in the backend folder i had to do `npm install` instead of the `npm install --prod` from the manual installation instructions.

**Comment by wiz** [comment]
Thanks for reporting this, you are correct, we use --no-optional so the --prod is a mistake
