### ISSUE TITLE
Electrum backend failure (introduced in 543c1ce)

### ISSUE THREAD

**Issue by erikarvstedt** [mempool/mempool#1974]
When running mempool with backend `electrum`, address-related API functions fail with error `sha256 is not a function`.
Example:
```
curl -s http://localhost:8999/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv; echo
curl -s https://mempool.nixbitcoin.org/api/v1/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv; echo
#=> sha256 is not a function
```
Bisecting shows that this error was introduced in https://github.com/mempool/mempool/commit/543c1cee62db5e1f396e3d713bae51b955cc4522.

I've reproduced this by building the backend like in `ci.yml` and running it in a nix-bitcoin container environment. So this bug  should be easily reproducible with docker.
